[models]
provider = "ChatOpenAI"

[models.args]
model = "llama-3-3-70b-instruct"

[models.environment]
OPENAI_API_KEY = "dummy"
OPENAI_API_BASE = "https://route-llama-70b-ai-composer.apps.salamander.aimlworkbench.com/v1"
